app = "neocred-backend"
primary_region = "nrt"

[build]

[env]
  PORT = "8080"
  HOST = "0.0.0.0"
  ENVIRONMENT = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  grace_period = "10s"
  method = "GET"
  path = "/health"
  protocol = "http"
  timeout = "5s"

[machine]
  memory = "1024mb"
  cpu_kind = "shared"
  cpus = 1